### DISCUSSION TITLE
Links re-formatting after edits made

### DISCUSSION THREAD

**Discussion by ashleybiermannalaska** [emagers/ab-story-validation-action#51] [Q&A] [answered]
I'm finding an issue when the checks run after the link has been converted from the `AB#` format to the link `[Name](url)` format. Where the validation passed the initial time, it fails after the change. Anyone know of ways to avoid false negatives?
@emagers

**Comment by emagers** [comment]
> I'm finding an issue when the checks run after the link has been converted from the `AB#` format to the link `[Name](url)` format. Where the validation passed the initial time, it fails after the change. Anyone know of ways to avoid false negatives?
> @emagers 

Hi @ashleybiermannalaska, would you be able to provide the action run logs to help identify the issue?

**Reply by ashleybiermannalaska** [reply]
Hi @emagers , thank you for the quick reply! here's some more info: 

steps to reproduce: 
1. write description using format `AB#123`
2. save
3. push change to PR (which triggers another story validation)
4. story validation fails (AB link is now in format `[AB123](url)`)
5. action log error

![Screenshot 2023-12-15 at 4 30 01 PM](https://github.com/emagers/ab-story-validation-action/assets/113386737/49bbf19d-64a5-4994-8baa-0f7aee0e5663)

6. edit AB link to be in correct format `AB#123`
7. save
8. story validation triggers and passes

**Reply by emagers** [reply]
Interesting. From the logs it appears that there's some kind of auth issue going on likely when the action is making the GraphQL call to get the PR comments. Not sure why this would be happening only on changes pushed to the PR and not on updates to the comments though. I'll try to repro it this weekend. 

Is this happening on all repos you're running the action on?

**Reply by ashleybiermannalaska** [reply]
Yes, we have it on 4 repos and they are all experiencing it. We did go through some pipeline changes over the last week, and upgraded from @v1.0.0 to v2.0.1. 

for what it's worth, here's our yml

```
name: Story Number Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  story-number-validation:
    name: Story Number Validation
    runs-on: ubuntu-latest
    steps:
      - name: ab-story-validation
        uses: emagers/ab-story-validation-action@v2.0.1
        if: contains(github.actor, '[bot]') == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
